import {
  Case,
  MediaItem,
  Finding,
  EvidenceGroup,
  EvidenceLink,
  TimelineEntry,
  ProcessingStats,
} from './types';

export interface DemoData {
  case: Case;
  mediaItems: MediaItem[];
  findings: Finding[];
  evidenceGroups: EvidenceGroup[];
  evidenceLinks: EvidenceLink[];
  timeline: TimelineEntry[];
  stats: ProcessingStats;
}

export function getDemoCase(): DemoData {
  const caseId = 'demo-case-1';

  const demoCase: Case = {
    id: caseId,
    name: 'Vehicle Collision — Highway 101 — October 2026',
    type: 'vehicle_incident',
    description:
      'Multi-vehicle collision on Highway 101 near exit 42. Significant front and left-side damage to primary vehicle. Documentation captured at scene by responding officer.',
    status: 'completed',
    createdAt: '2026-10-03T14:30:00Z',
    updatedAt: '2026-10-03T14:40:00Z',
    mediaCount: 15,
    usefulCount: 12,
    duplicateCount: 2,
    lowQualityCount: 1,
    evidenceGroupCount: 6,
    findingCount: 6,
  };

  const mediaItems: MediaItem[] = [
    {
      id: 'demo-media-1',
      caseId,
      filename: 'IMG_3421.jpg',
      originalFilename: 'IMG_3421.jpg',
      type: 'image',
      mimeType: 'image/jpeg',
      cloudinaryPublicId: 'evitrace/demo/IMG_3421',
      cloudinaryUrl: '/demo/IMG_3421.jpg',
      thumbnailUrl: '/demo/IMG_3421.jpg',
      width: 4032,
      height: 3024,
      size: 2048000,
      timestamp: '2026-10-03T14:31:00Z',
      hash: 'a1b2c3d4e5f6',
      qualityScore: 92,
      clarityScore: 94,
      resolutionScore: 96,
      relevanceScore: 98,
      caption: 'Wide shot of collision scene showing both vehicles at highway intersection',
      categories: ['scene', 'overview', 'vehicles', 'highway'],
      status: 'analyzed',
      isDuplicate: false,
      isLowQuality: false,
      evidenceGroupId: 'demo-group-5',
      uploadedAt: '2026-10-03T14:31:00Z',
    },
    {
      id: 'demo-media-2',
      caseId,
      filename: 'IMG_3422.jpg',
      originalFilename: 'IMG_3422.jpg',
      type: 'image',
      mimeType: 'image/jpeg',
      cloudinaryPublicId: 'evitrace/demo/IMG_3422',
      cloudinaryUrl: '/demo/IMG_3422.jpg',
      thumbnailUrl: '/demo/IMG_3422.jpg',
      width: 4032,
      height: 3024,
      size: 1848000,
      timestamp: '2026-10-03T14:31:30Z',
      hash: 'b2c3d4e5f6g7',
      qualityScore: 94,
      clarityScore: 96,
      resolutionScore: 95,
      relevanceScore: 97,
      caption: 'Front bumper showing significant deformation and paint transfer',
      categories: ['vehicle', 'front bumper', 'damage', 'deformation'],
      status: 'analyzed',
      isDuplicate: false,
      isLowQuality: false,
      evidenceGroupId: 'demo-group-1',
      uploadedAt: '2026-10-03T14:31:30Z',
    },
    {
      id: 'demo-media-3',
      caseId,
      filename: 'IMG_3423.jpg',
      originalFilename: 'IMG_3423.jpg',
      type: 'image',
      mimeType: 'image/jpeg',
      cloudinaryPublicId: 'evitrace/demo/IMG_3423',
      cloudinaryUrl: '/demo/IMG_3423.jpg',
      thumbnailUrl: '/demo/IMG_3423.jpg',
      width: 4032,
      height: 3024,
      size: 1948000,
      timestamp: '2026-10-03T14:32:00Z',
      hash: 'c3d4e5f6g7h8',
      qualityScore: 91,
      clarityScore: 93,
      resolutionScore: 94,
      relevanceScore: 95,
      caption: 'Front bumper damage from different angle showing crumple pattern',
      categories: ['vehicle', 'front bumper', 'damage', 'crumple'],
      status: 'analyzed',
      isDuplicate: false,
      isLowQuality: false,
      evidenceGroupId: 'demo-group-1',
      uploadedAt: '2026-10-03T14:32:00Z',
    },
    {
      id: 'demo-media-4',
      caseId,
      filename: 'IMG_3424.jpg',
      originalFilename: 'IMG_3424.jpg',
      type: 'image',
      mimeType: 'image/jpeg',
      cloudinaryPublicId: 'evitrace/demo/IMG_3424',
      cloudinaryUrl: '/demo/IMG_3424.jpg',
      thumbnailUrl: '/demo/IMG_3424.jpg',
      width: 4032,
      height: 3024,
      size: 2148000,
      timestamp: '2026-10-03T14:32:30Z',
      hash: 'd4e5f6g7h8i9',
      qualityScore: 87,
      clarityScore: 89,
      resolutionScore: 90,
      relevanceScore: 88,
      caption: 'Left headlight assembly showing crack in housing and misalignment',
      categories: ['vehicle', 'headlight', 'damage', 'crack'],
      status: 'analyzed',
      isDuplicate: false,
      isLowQuality: false,
      evidenceGroupId: 'demo-group-2',
      uploadedAt: '2026-10-03T14:32:30Z',
    },
    {
      id: 'demo-media-5',
      caseId,
      filename: 'IMG_3425.jpg',
      originalFilename: 'IMG_3425.jpg',
      type: 'image',
      mimeType: 'image/jpeg',
      cloudinaryPublicId: 'evitrace/demo/IMG_3425',
      cloudinaryUrl: '/demo/IMG_3425.jpg',
      thumbnailUrl: '/demo/IMG_3425.jpg',
      width: 4032,
      height: 3024,
      size: 1748000,
      timestamp: '2026-10-03T14:33:00Z',
      hash: 'e5f6g7h8i9j0',
      qualityScore: 93,
      clarityScore: 91,
      resolutionScore: 94,
      relevanceScore: 92,
      caption: 'Left side door showing lateral scraping and paint damage',
      categories: ['vehicle', 'left door', 'damage', 'scraping'],
      status: 'analyzed',
      isDuplicate: false,
      isLowQuality: false,
      evidenceGroupId: 'demo-group-3',
      uploadedAt: '2026-10-03T14:33:00Z',
    },
    {
      id: 'demo-media-6',
      caseId,
      filename: 'IMG_3426.jpg',
      originalFilename: 'IMG_3426.jpg',
      type: 'image',
      mimeType: 'image/jpeg',
      cloudinaryPublicId: 'evitrace/demo/IMG_3426',
      cloudinaryUrl: '/demo/IMG_3426.jpg',
      thumbnailUrl: '/demo/IMG_3426.jpg',
      width: 4032,
      height: 3024,
      size: 1648000,
      timestamp: '2026-10-03T14:33:30Z',
      hash: 'f6g7h8i9j0k1',
      qualityScore: 90,
      clarityScore: 92,
      resolutionScore: 91,
      relevanceScore: 89,
      caption: 'Close-up of left door scraping showing depth and metal exposure',
      categories: ['vehicle', 'left door', 'damage', 'close-up'],
      status: 'analyzed',
      isDuplicate: false,
      isLowQuality: false,
      evidenceGroupId: 'demo-group-3',
      uploadedAt: '2026-10-03T14:33:30Z',
    },
    {
      id: 'demo-media-7',
      caseId,
      filename: 'IMG_3427.jpg',
      originalFilename: 'IMG_3427.jpg',
      type: 'image',
      mimeType: 'image/jpeg',
      cloudinaryPublicId: 'evitrace/demo/IMG_3427',
      cloudinaryUrl: '/demo/IMG_3427.jpg',
      thumbnailUrl: '/demo/IMG_3427.jpg',
      width: 4032,
      height: 3024,
      size: 1548000,
      timestamp: '2026-10-03T14:34:00Z',
      hash: 'g7h8i9j0k1l2',
      qualityScore: 82,
      clarityScore: 84,
      resolutionScore: 86,
      relevanceScore: 80,
      caption: 'Front left wheel well showing liner displacement and fender buckling',
      categories: ['vehicle', 'wheel well', 'damage', 'fender'],
      status: 'analyzed',
      isDuplicate: false,
      isLowQuality: false,
      evidenceGroupId: 'demo-group-4',
      uploadedAt: '2026-10-03T14:34:00Z',
    },
    {
      id: 'demo-media-8',
      caseId,
      filename: 'IMG_3428.jpg',
      originalFilename: 'IMG_3428.jpg',
      type: 'image',
      mimeType: 'image/jpeg',
      cloudinaryPublicId: 'evitrace/demo/IMG_3428',
      cloudinaryUrl: '/demo/IMG_3428.jpg',
      thumbnailUrl: '/demo/IMG_3428.jpg',
      width: 4032,
      height: 3024,
      size: 1448000,
      timestamp: '2026-10-03T14:34:30Z',
      hash: 'h8i9j0k1l2m3',
      qualityScore: 88,
      clarityScore: 90,
      resolutionScore: 92,
      relevanceScore: 65,
      caption: 'Vehicle interior dashboard and steering column — no visible damage',
      categories: ['vehicle', 'interior', 'dashboard'],
      status: 'analyzed',
      isDuplicate: false,
      isLowQuality: false,
      evidenceGroupId: 'demo-group-6',
      uploadedAt: '2026-10-03T14:34:30Z',
    },
    {
      id: 'demo-media-9',
      caseId,
      filename: 'IMG_3429.jpg',
      originalFilename: 'IMG_3429.jpg',
      type: 'image',
      mimeType: 'image/jpeg',
      cloudinaryPublicId: 'evitrace/demo/IMG_3429',
      cloudinaryUrl: '/demo/IMG_3429.jpg',
      thumbnailUrl: '/demo/IMG_3429.jpg',
      width: 4032,
      height: 3024,
      size: 1348000,
      timestamp: '2026-10-03T14:35:00Z',
      hash: 'i9j0k1l2m3n4',
      qualityScore: 85,
      clarityScore: 87,
      resolutionScore: 89,
      relevanceScore: 60,
      caption: 'Rear of vehicle showing no visible damage to trunk or taillights',
      categories: ['vehicle', 'rear', 'undamaged'],
      status: 'analyzed',
      isDuplicate: false,
      isLowQuality: false,
      evidenceGroupId: 'demo-group-6',
      uploadedAt: '2026-10-03T14:35:00Z',
    },
    {
      id: 'demo-media-10',
      caseId,
      filename: 'IMG_3430.jpg',
      originalFilename: 'IMG_3430.jpg',
      type: 'image',
      mimeType: 'image/jpeg',
      cloudinaryPublicId: 'evitrace/demo/IMG_3430',
      cloudinaryUrl: '/demo/IMG_3430.jpg',
      thumbnailUrl: '/demo/IMG_3430.jpg',
      width: 4032,
      height: 3024,
      size: 1248000,
      timestamp: '2026-10-03T14:35:30Z',
      hash: 'j0k1l2m3n4o5',
      qualityScore: 86,
      clarityScore: 88,
      resolutionScore: 90,
      relevanceScore: 75,
      caption: 'Rear license plate for vehicle identification',
      categories: ['vehicle', 'license plate', 'identification'],
      status: 'analyzed',
      isDuplicate: false,
      isLowQuality: false,
      evidenceGroupId: 'demo-group-6',
      uploadedAt: '2026-10-03T14:35:30Z',
    },
    {
      id: 'demo-media-11',
      caseId,
      filename: 'IMG_3431.jpg',
      originalFilename: 'IMG_3431.jpg',
      type: 'image',
      mimeType: 'image/jpeg',
      cloudinaryPublicId: 'evitrace/demo/IMG_3431',
      cloudinaryUrl: '/demo/IMG_3431.jpg',
      thumbnailUrl: '/demo/IMG_3431.jpg',
      width: 4032,
      height: 3024,
      size: 1848000,
      timestamp: '2026-10-03T14:36:00Z',
      hash: 'b2c3d4e5f6g7',
      qualityScore: 91,
      clarityScore: 93,
      resolutionScore: 92,
      relevanceScore: 94,
      caption: 'Front bumper — near-duplicate of IMG_3422 (slightly different crop)',
      categories: ['vehicle', 'front bumper', 'damage'],
      status: 'duplicate',
      isDuplicate: true,
      duplicateOf: 'demo-media-2',
      isLowQuality: false,
      evidenceGroupId: 'demo-group-1',
      uploadedAt: '2026-10-03T14:36:00Z',
    },
    {
      id: 'demo-media-12',
      caseId,
      filename: 'IMG_3432.jpg',
      originalFilename: 'IMG_3432.jpg',
      type: 'image',
      mimeType: 'image/jpeg',
      cloudinaryPublicId: 'evitrace/demo/IMG_3432',
      cloudinaryUrl: '/demo/IMG_3432.jpg',
      thumbnailUrl: '/demo/IMG_3432.jpg',
      width: 4032,
      height: 3024,
      size: 1748000,
      timestamp: '2026-10-03T14:36:30Z',
      hash: 'e5f6g7h8i9j0',
      qualityScore: 89,
      clarityScore: 88,
      resolutionScore: 90,
      relevanceScore: 87,
      caption: 'Left door scraping — near-duplicate of IMG_3425',
      categories: ['vehicle', 'left door', 'damage'],
      status: 'duplicate',
      isDuplicate: true,
      duplicateOf: 'demo-media-5',
      isLowQuality: false,
      evidenceGroupId: 'demo-group-3',
      uploadedAt: '2026-10-03T14:36:30Z',
    },
    {
      id: 'demo-media-13',
      caseId,
      filename: 'IMG_3433.jpg',
      originalFilename: 'IMG_3433.jpg',
      type: 'image',
      mimeType: 'image/jpeg',
      cloudinaryPublicId: 'evitrace/demo/IMG_3433',
      cloudinaryUrl: '/demo/IMG_3433.jpg',
      thumbnailUrl: '/demo/IMG_3433.jpg',
      width: 2048,
      height: 1536,
      size: 848000,
      timestamp: '2026-10-03T14:37:00Z',
      hash: 'k1l2m3n4o5p6',
      qualityScore: 35,
      clarityScore: 22,
      resolutionScore: 45,
      relevanceScore: 40,
      caption: 'Blurry shot — motion blur prevents useful damage assessment',
      categories: ['vehicle', 'blurry', 'unusable'],
      status: 'low_quality',
      isDuplicate: false,
      isLowQuality: true,
      uploadedAt: '2026-10-03T14:37:00Z',
    },
    {
      id: 'demo-media-14',
      caseId,
      filename: 'VID_0891.mp4',
      originalFilename: 'VID_0891.mp4',
      type: 'video',
      mimeType: 'video/mp4',
      cloudinaryPublicId: 'evitrace/demo/VID_0891',
      cloudinaryUrl: '/demo/VID_0891.jpg',
      thumbnailUrl: '/demo/VID_0891.jpg',
      width: 1920,
      height: 1080,
      size: 24480000,
      duration: 45,
      timestamp: '2026-10-03T14:37:30Z',
      hash: 'l2m3n4o5p6q7',
      qualityScore: 90,
      clarityScore: 88,
      resolutionScore: 92,
      relevanceScore: 95,
      caption: 'Walk-around video documenting full extent of front and side damage',
      categories: ['vehicle', 'walk-around', 'video', 'damage overview'],
      status: 'analyzed',
      isDuplicate: false,
      isLowQuality: false,
      evidenceGroupId: 'demo-group-5',
      uploadedAt: '2026-10-03T14:37:30Z',
    },
    {
      id: 'demo-media-15',
      caseId,
      filename: 'IMG_3434.jpg',
      originalFilename: 'IMG_3434.jpg',
      type: 'image',
      mimeType: 'image/jpeg',
      cloudinaryPublicId: 'evitrace/demo/IMG_3434',
      cloudinaryUrl: '/demo/IMG_3434.jpg',
      thumbnailUrl: '/demo/IMG_3434.jpg',
      width: 4032,
      height: 3024,
      size: 2048000,
      timestamp: '2026-10-03T14:38:00Z',
      hash: 'm3n4o5p6q7r8',
      qualityScore: 89,
      clarityScore: 91,
      resolutionScore: 93,
      relevanceScore: 85,
      caption: 'Road surface showing skid marks and debris at collision point',
      categories: ['scene', 'road', 'skid marks', 'evidence'],
      status: 'analyzed',
      isDuplicate: false,
      isLowQuality: false,
      evidenceGroupId: 'demo-group-5',
      uploadedAt: '2026-10-03T14:38:00Z',
    },
  ];

  const findings: Finding[] = [
    {
      id: 'demo-finding-1',
      caseId,
      title: 'Significant Front Bumper Deformation',
      description:
        'Visible deformation and surface damage are present around the front bumper area. Paint transfer from the other vehicle is evident, suggesting a direct frontal impact.',
      confidence: 94,
      category: 'structural_damage',
      evidenceGroupId: 'demo-group-1',
    },
    {
      id: 'demo-finding-2',
      caseId,
      title: 'Headlight Housing Crack and Misalignment',
      description:
        'The left headlight assembly shows a crack in the outer housing and appears to be displaced from its mounting. Internal reflector damage is also visible.',
      confidence: 87,
      category: 'component_damage',
      evidenceGroupId: 'demo-group-2',
    },
    {
      id: 'demo-finding-3',
      caseId,
      title: 'Lateral Scraping Along Left Door Panels',
      description:
        'Extensive lateral scraping damage runs along the left front and rear door panels. Paint has been removed to expose bare metal in several areas.',
      confidence: 91,
      category: 'surface_damage',
      evidenceGroupId: 'demo-group-3',
    },
    {
      id: 'demo-finding-4',
      caseId,
      title: 'Wheel Well Liner Displacement and Fender Damage',
      description:
        'The front left wheel well liner has been pushed inward, and the fender shows buckling consistent with lateral impact force.',
      confidence: 78,
      category: 'structural_damage',
      evidenceGroupId: 'demo-group-4',
    },
    {
      id: 'demo-finding-5',
      caseId,
      title: 'Multi-Vehicle Collision at Highway Intersection',
      description:
        'Scene documentation confirms a multi-vehicle collision at or near a highway intersection. Skid marks and debris field are consistent with high-speed impact.',
      confidence: 96,
      category: 'scene_analysis',
      evidenceGroupId: 'demo-group-5',
    },
    {
      id: 'demo-finding-6',
      caseId,
      title: 'Vehicle Identification and Interior Condition',
      description:
        'Vehicle identification captured via license plate. Interior shows no visible damage to dashboard, steering column, or seating. Airbags did not deploy.',
      confidence: 85,
      category: 'identification',
      evidenceGroupId: 'demo-group-6',
    },
  ];

  const evidenceGroups: EvidenceGroup[] = [
    {
      id: 'demo-group-1',
      caseId,
      title: 'Front Bumper Damage',
      description:
        'Multiple photos documenting front bumper deformation, paint transfer, and crumple patterns from the primary impact point.',
      confidence: 94,
      category: 'structural_damage',
      mediaItems: mediaItems.filter((m) => m.evidenceGroupId === 'demo-group-1'),
      findings: findings.filter((f) => f.evidenceGroupId === 'demo-group-1'),
      strongestMediaId: 'demo-media-2',
    },
    {
      id: 'demo-group-2',
      caseId,
      title: 'Headlight Assembly',
      description:
        'Close-up documentation of left headlight housing damage, including crack and displacement.',
      confidence: 87,
      category: 'component_damage',
      mediaItems: mediaItems.filter((m) => m.evidenceGroupId === 'demo-group-2'),
      findings: findings.filter((f) => f.evidenceGroupId === 'demo-group-2'),
      strongestMediaId: 'demo-media-4',
    },
    {
      id: 'demo-group-3',
      caseId,
      title: 'Left Side Door Damage',
      description:
        'Lateral scraping damage along left door panels showing paint removal and metal exposure.',
      confidence: 91,
      category: 'surface_damage',
      mediaItems: mediaItems.filter((m) => m.evidenceGroupId === 'demo-group-3'),
      findings: findings.filter((f) => f.evidenceGroupId === 'demo-group-3'),
      strongestMediaId: 'demo-media-5',
    },
    {
      id: 'demo-group-4',
      caseId,
      title: 'Wheel Well Impact',
      description:
        'Front left wheel well liner displacement and fender buckling from lateral impact.',
      confidence: 78,
      category: 'structural_damage',
      mediaItems: mediaItems.filter((m) => m.evidenceGroupId === 'demo-group-4'),
      findings: findings.filter((f) => f.evidenceGroupId === 'demo-group-4'),
      strongestMediaId: 'demo-media-7',
    },
    {
      id: 'demo-group-5',
      caseId,
      title: 'Scene Overview',
      description:
        'Wide-angle scene documentation, walk-around video, and road surface evidence.',
      confidence: 96,
      category: 'scene_analysis',
      mediaItems: mediaItems.filter((m) => m.evidenceGroupId === 'demo-group-5'),
      findings: findings.filter((f) => f.evidenceGroupId === 'demo-group-5'),
      strongestMediaId: 'demo-media-1',
    },
    {
      id: 'demo-group-6',
      caseId,
      title: 'Vehicle Identification',
      description:
        'License plate capture, interior condition documentation, and rear vehicle condition.',
      confidence: 85,
      category: 'identification',
      mediaItems: mediaItems.filter((m) => m.evidenceGroupId === 'demo-group-6'),
      findings: findings.filter((f) => f.evidenceGroupId === 'demo-group-6'),
      strongestMediaId: 'demo-media-10',
    },
  ];

  const evidenceLinks: EvidenceLink[] = [
    { id: 'demo-link-1', findingId: 'demo-finding-1', mediaId: 'demo-media-2', reason: 'Primary damage evidence — clear frontal view of bumper deformation', strength: 95 },
    { id: 'demo-link-2', findingId: 'demo-finding-1', mediaId: 'demo-media-3', reason: 'Corroborating angle confirms extent of crumple damage', strength: 92 },
    { id: 'demo-link-3', findingId: 'demo-finding-1', mediaId: 'demo-media-14', reason: 'Walk-around video provides dynamic perspective of damage', strength: 85 },
    { id: 'demo-link-4', findingId: 'demo-finding-2', mediaId: 'demo-media-4', reason: 'Close-up detail of headlight crack and housing displacement', strength: 88 },
    { id: 'demo-link-5', findingId: 'demo-finding-3', mediaId: 'demo-media-5', reason: 'Primary evidence of lateral scraping along door panels', strength: 93 },
    { id: 'demo-link-6', findingId: 'demo-finding-3', mediaId: 'demo-media-6', reason: 'Close-up confirms scraping depth and metal exposure', strength: 89 },
    { id: 'demo-link-7', findingId: 'demo-finding-4', mediaId: 'demo-media-7', reason: 'Clearly shows wheel well liner displacement and fender buckling', strength: 79 },
    { id: 'demo-link-8', findingId: 'demo-finding-5', mediaId: 'demo-media-1', reason: 'Wide shot establishes full scene context and vehicle positions', strength: 98 },
    { id: 'demo-link-9', findingId: 'demo-finding-5', mediaId: 'demo-media-14', reason: 'Video walk-around documents overall collision scene', strength: 94 },
    { id: 'demo-link-10', findingId: 'demo-finding-5', mediaId: 'demo-media-15', reason: 'Road surface evidence with skid marks corroborates collision dynamics', strength: 87 },
    { id: 'demo-link-11', findingId: 'demo-finding-6', mediaId: 'demo-media-10', reason: 'Provides clear vehicle identification via license plate', strength: 99 },
    { id: 'demo-link-12', findingId: 'demo-finding-6', mediaId: 'demo-media-8', reason: 'Documents interior condition — no visible damage or airbag deployment', strength: 82 },
    { id: 'demo-link-13', findingId: 'demo-finding-6', mediaId: 'demo-media-9', reason: 'Confirms rear of vehicle undamaged', strength: 75 },
  ];

  const timeline: TimelineEntry[] = [
    {
      id: 'demo-timeline-1',
      mediaId: 'demo-media-1',
      timestamp: '2026-10-03T14:31:00Z',
      label: 'Scene overview captured',
      description: 'Wide shot of the collision scene with both vehicles visible',
      thumbnailUrl: '/demo/IMG_3421.jpg',
      isEstimated: false,
    },
    {
      id: 'demo-timeline-2',
      mediaId: 'demo-media-2',
      timestamp: '2026-10-03T14:31:30Z',
      label: 'Front bumper close-up',
      description: 'Detailed capture of front bumper deformation',
      thumbnailUrl: '/demo/IMG_3422.jpg',
      isEstimated: false,
    },
    {
      id: 'demo-timeline-3',
      mediaId: 'demo-media-3',
      timestamp: '2026-10-03T14:32:00Z',
      label: 'Front bumper alternate angle',
      description: 'Different perspective on crumple pattern',
      thumbnailUrl: '/demo/IMG_3423.jpg',
      isEstimated: false,
    },
    {
      id: 'demo-timeline-4',
      mediaId: 'demo-media-4',
      timestamp: '2026-10-03T14:32:30Z',
      label: 'Headlight damage',
      description: 'Close-up of headlight housing crack',
      thumbnailUrl: '/demo/IMG_3424.jpg',
      isEstimated: false,
    },
    {
      id: 'demo-timeline-5',
      mediaId: 'demo-media-5',
      timestamp: '2026-10-03T14:33:00Z',
      label: 'Left door scraping',
      description: 'Lateral scraping damage along door panels',
      thumbnailUrl: '/demo/IMG_3425.jpg',
      isEstimated: false,
    },
    {
      id: 'demo-timeline-6',
      mediaId: 'demo-media-6',
      timestamp: '2026-10-03T14:33:30Z',
      label: 'Door damage close-up',
      description: 'Detail showing scraping depth and metal exposure',
      thumbnailUrl: '/demo/IMG_3426.jpg',
      isEstimated: false,
    },
    {
      id: 'demo-timeline-7',
      mediaId: 'demo-media-7',
      timestamp: '2026-10-03T14:34:00Z',
      label: 'Wheel well inspection',
      description: 'Liner displacement and fender buckling',
      thumbnailUrl: '/demo/IMG_3427.jpg',
      isEstimated: false,
    },
    {
      id: 'demo-timeline-8',
      mediaId: 'demo-media-8',
      timestamp: '2026-10-03T14:34:30Z',
      label: 'Interior check',
      description: 'Dashboard and steering — no damage',
      thumbnailUrl: '/demo/IMG_3428.jpg',
      isEstimated: false,
    },
    {
      id: 'demo-timeline-9',
      mediaId: 'demo-media-10',
      timestamp: '2026-10-03T14:35:30Z',
      label: 'Vehicle identification',
      description: 'License plate captured for records',
      thumbnailUrl: '/demo/IMG_3430.jpg',
      isEstimated: false,
    },
    {
      id: 'demo-timeline-10',
      mediaId: 'demo-media-14',
      timestamp: '2026-10-03T14:37:30Z',
      label: 'Walk-around video',
      description: '45-second walk-around documenting full damage extent',
      thumbnailUrl: '/demo/VID_0891.jpg',
      isEstimated: false,
    },
    {
      id: 'demo-timeline-11',
      mediaId: 'demo-media-15',
      timestamp: '2026-10-03T14:38:00Z',
      label: 'Road evidence',
      description: 'Skid marks and debris at collision point',
      thumbnailUrl: '/demo/IMG_3434.jpg',
      isEstimated: false,
    },
  ];

  const stats: ProcessingStats = {
    totalFiles: 15,
    uniqueAssets: 12,
    duplicatesDetected: 2,
    lowQualityAssets: 1,
    evidenceGroups: 6,
    visualFindings: 6,
  };

  return {
    case: demoCase,
    mediaItems,
    findings,
    evidenceGroups,
    evidenceLinks,
    timeline,
    stats,
  };
}
